import { invokeOrMock, isTauri } from './shared'

export type ProviderKind = 'asr' | 'llm' | 'omni'

export type AuthRequirement =
  | 'none'
  | 'api_key'
  | 'endpoint_model_optional_api_key'
  | 'api_key_unless_custom_endpoint'
  | 'volcengine'
  | 'xfyun'
  | 'o_auth'

export interface ProviderDescriptor {
  kind: ProviderKind
  providerType: string
  labelKey: string
  defaultEndpoint: string | null
  defaultModel: string | null
  authRequirement: AuthRequirement
  validationProbe: string
  staticModels: string[]
}

/** Core owns protocol, defaults, and credential requirements. */
export async function listProviderDescriptors(kind: ProviderKind): Promise<ProviderDescriptor[]> {
  if (!isTauri) {
    // Generated by Core; keep browser previews usable without duplicating
    // provider defaults or authentication rules in handwritten frontend data.
    const { default: catalog } = await import('./provider-descriptors.generated.json')
    return catalog[kind] as ProviderDescriptor[]
  }
  return invokeOrMock('list_provider_descriptors', { kind }, () => [])
}
